# Generated by Django 5.2 on 2025-06-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ibloguser',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='email address'),
        ),
    ]
