# Generated by Django 5.2 on 2025-06-01 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_category_options_alter_blogpost_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ibloguser',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='email address'),
        ),
    ]
