# Generated by Django 5.2 on 2025-06-10 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_ibloguser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='blog_post',
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
