# Generated by Django 5.2 on 2025-06-10 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Blog Title')),
                ('slug', models.CharField(max_length=200, verbose_name='slug')),
                ('content', models.TextField(verbose_name='Content')),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('featured_img', models.ImageField(blank=True, upload_to='featured_images')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, default='Uncategorized', max_length=50)),
                ('blog_post', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blogs.blogpost')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
