# Generated by Django 5.2 on 2025-06-10 22:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ibloguser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='ibloguser',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ibloguser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ibloguser',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
