# Generated by Django 5.2 on 2025-09-11 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ibloguser',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='ibloguser',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
